.TH "DOCKER" "1" "APRIL 2014" "Docker User Manuals" ""
.SH NAME
.PP
docker\-port \- Lookup the public\-facing port which is NAT\-ed to
PRIVATE_PORT
.SH SYNOPSIS
.PP
\f[B]docker port\f[] CONTAINER PRIVATE_PORT
.SH DESCRIPTION
.PP
Lookup the public\-facing port which is NAT\-ed to PRIVATE_PORT
.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot
com) based on docker.io source material and internal work.
.SH AUTHORS
William Henry.
