.TH "DOCKER" "1" "APRIL 2014" "Docker User Manuals" ""
.SH NAME
.PP
docker\-top \- Lookup the running processes of a container
.SH SYNOPSIS
.PP
\f[B]docker top\f[] CONTAINER [ps\-OPTION]
.SH DESCRIPTION
.PP
Look up the running process of the container.
ps\-OPTION can be any of the options you would pass to a Linux ps
command.
.SH EXAMPLE
.PP
Run \f[B]docker top\f[] with the ps option of \-x:
.IP
.nf
\f[C]
$\ sudo\ docker\ top\ 8601afda2b\ \-x
PID\ \ \ \ \ \ TTY\ \ \ \ \ \ \ STAT\ \ \ \ \ \ \ TIME\ \ \ \ \ \ \ \ \ COMMAND
16623\ \ \ \ ?\ \ \ \ \ \ \ \ \ Ss\ \ \ \ \ \ \ \ \ 0:00\ \ \ \ \ \ \ \ \ sleep\ 99999
\f[]
.fi
.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot
com) based on docker.io source material and internal work.
.SH AUTHORS
William Henry.
