.TH "DOCKER" "1" "APRIL 2014" "Docker User Manuals" ""
.SH NAME
.PP
docker\-login \- Register or Login to a docker registry server.
.SH SYNOPSIS
.PP
\f[B]docker login\f[] [\f[B]\-e\f[]|\f[B]\-email\f[]=""]
[\f[B]\-p\f[]|\f[B]\-\-password\f[]=""]
[\f[B]\-u\f[]|\f[B]\-\-username\f[]=""] [SERVER]
.SH DESCRIPTION
.PP
Register or Login to a docker registry server, if no server is specified
"https://index.docker.io/v1/" is the default.
If you want to login to a private registry you can specify this by
adding the server name.
.SH OPTIONS
.PP
\f[B]\-e\f[], \f[B]\-\-email\f[]="" Email address
.PP
\f[B]\-p\f[], \f[B]\-\-password\f[]="" Password
.PP
\f[B]\-u\f[], \f[B]\-\-username\f[]="" Username
.SH EXAMPLE
.SS Login to a local registry
.IP
.nf
\f[C]
#\ docker\ login\ localhost:8080
\f[]
.fi
.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot
com) based on docker.io source material and internal work.
.SH AUTHORS
William Henry.
