.TH "DOCKER" "1" "APRIL 2014" "Docker User Manuals" ""
.SH NAME
.PP
docker\-logs \- Fetch the logs of a container
.SH SYNOPSIS
.PP
\f[B]docker logs\f[] \f[B]\-\-follow\f[][=\f[I]false\f[]] CONTAINER
.SH DESCRIPTION
.PP
The \f[B]docker logs\f[] command batch\-retrieves whatever logs are
present for a container at the time of execution.
This does not guarantee execution order when combined with a docker run
(i.e.
your run may not have generated any logs at the time you execute docker
logs).
.PP
The \f[B]docker logs \-\-follow\f[] command combines commands
\f[B]docker logs\f[] and \f[B]docker attach\f[].
It will first return all logs from the beginning and then continue
streaming new output from the container's stdout and stderr.
.SH OPTIONS
.PP
\f[B]\-f, \-\-follow\f[]=\f[I]true\f[]|\f[I]false\f[] When
\f[I]true\f[], follow log output.
The default is false.
.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot
com) based on docker.io source material and internal work.
.SH AUTHORS
William Henry.
