.TH "DOCKER" "1" "APRIL 2014" "Docker User Manuals" ""
.SH NAME
.PP
docker\-save \- Save an image to a tar archive (streamed to STDOUT by
default)
.SH SYNOPSIS
.PP
\f[B]docker save\f[] [\f[B]\-o\f[]|\f[B]\-\-output\f[]=""] IMAGE
.SH DESCRIPTION
.PP
Produces a tarred repository to the standard output stream.
Contains all parent layers, and all tags + versions, or specified
repo:tag.
.PP
Stream to a file instead of STDOUT by using \f[B]\-o\f[].
.SH OPTIONS
.PP
\f[B]\-o\f[], \f[B]\-\-output\f[]="" Write to an file, instead of STDOUT
.SH EXAMPLE
.PP
Save all fedora repository images to a fedora\-all.tar and save the
latest fedora image to a fedora\-latest.tar:
.IP
.nf
\f[C]
$\ sudo\ docker\ save\ fedora\ >\ fedora\-all.tar
$\ sudo\ docker\ save\ \-\-output=fedora\-latest.tar\ fedora:latest
$\ ls\ \-sh\ fedora\-all.tar
721M\ fedora\-all.tar
$\ ls\ \-sh\ fedora\-latest.tar
367M\ fedora\-latest.tar
\f[]
.fi
.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot
com) based on docker.io source material and internal work.
.SH AUTHORS
William Henry.
