.TH "DOCKER" "1" "APRIL 2014" "Docker User Manuals" ""
.SH NAME
.PP
docker\-tag \- Tag an image in the repository
.SH SYNOPSIS
.PP
\f[B]docker tag\f[] [\f[B]\-f\f[]|\f[B]\-\-force\f[][=\f[I]false\f[]]
IMAGE [REGISTRYHOST/][USERNAME/]NAME[:TAG]
.SH DESCRIPTION
.PP
This will tag an image in the repository.
.SH "OPTIONS"
.PP
\f[B]\-f\f[], \f[B]\-\-force\f[]=\f[I]true\f[]|\f[I]false\f[] When set
to true, force the tag name.
The default is \f[I]false\f[].
.PP
\f[B]REGISTRYHOST\f[] The hostname of the registry if required.
This may also include the port separated by a \[aq]:\[aq]
.PP
\f[B]USERNAME\f[] The username or other qualifying identifier for the
image.
.PP
\f[B]NAME\f[] The image name.
.PP
\f[B]TAG\f[] The tag you are assigning to the image.
.SH EXAMPLES
.SS Tagging an image
.PP
Here is an example of tagging an image with the tag version1.0 :
.IP
.nf
\f[C]
docker\ tag\ 0e5574283393\ fedora/httpd:version1.0
\f[]
.fi
.SS Tagging an image for a private repository
.PP
To push an image to an private registry and not the central Docker
registry you must tag it with the registry hostname and port (if
needed).
.IP
.nf
\f[C]
docker\ tag\ 0e5574283393\ myregistryhost:5000/fedora/httpd:version1.0
\f[]
.fi
.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot
com) based on docker.io source material and internal work.
.SH AUTHORS
William Henry.
